### ISSUE TITLE
Locality not returned

### ISSUE THREAD

**Issue by TariqAHassan** [pelias/pip-service#101]
Hi @orangejulius.

First, sorry to ping you directly, but I have been unable to resolve this issue for a while and am really quite confused about what is going on. In short, I have been unable to get the current version, or even prior versions, of this package to reliably return the locaility.

While it is true for the example on the homepage:

```bash
curl http://localhost:3102/-106.937/34.060
```

The following query for Austin TX only returns the neighbourhood:

```bash
curl http://localhost:3102/-97.7431/30.2672
```

Indeed, I found this to be true in many places in North America (try anywhere in Toronto, for example), at least w.r.t. my limited testing.

Of course, it is possible to solve for the locality by looking up the, say, neighbourhood's hierarchy in the WoF data...however, this is very tedious to implement.

Any idea on why this is happening? Is this happening by design?

Edit:

* Might this be related to: https://github.com/pelias/wof-admin-lookup/pull/246?

**Comment by Joxit** [comment]
Hello,

Is `data/101/724/577/101724577.geojson` present in your wof bundle path ?

**Comment by Joxit** [comment]
That's means you used  `--admin-only` without `imports.whosonfirst.importPlace` right ? 

That meas your missing locality may be related to https://github.com/whosonfirst/go-whosonfirst-dist/issues/9

**Comment by TariqAHassan** [comment]
@Joxit . Yes, that is correct.

Thanks to both of you for the help. I am planning to rebuild against the repo directly and report back.

**Comment by TariqAHassan** [comment]
Hi.

So I just finished building pelias (the whole geocoder) against a direct clone from the [whosonfirst-data/whosonfirst-data](https://github.com/whosonfirst-data/whosonfirst-data) repo. 

The locality issues have gone away. Thanks agin to both of you for the guidances.

**Comment by bboure** [comment]
Hi,

I am experiencing the same issue.
After checking the [compare tool](https://pelias.github.io/compare/#/v1/place?ids=openstreetmap:venue:relation/1243821), it does not seem like an issue in my build. Locality is also missing in https://api.geocode.earth

Places in Brussels do not get the `locality` property.

**Comment by missinglink** [comment]
@bboure your issue seems to be due to [neighbourhood:85801105](https://spelunker.whosonfirst.org/id/85801105/) being parented by [locality:101751573](https://spelunker.whosonfirst.org/id/101751573/) which is 'both deprecated and superseded by: 1175610569'.

Can you please comment on https://github.com/whosonfirst-data/whosonfirst-data/issues/1377 to let the WOF team know?

**Comment by bboure** [comment]
@orangejulius ok thanks

**Comment by missinglink** [comment]
Hi @bboure I've written a script to fix the outdated WOF hierarchies.
I'd appreciate if you could test out my fix before I write the code to patch all the files on the CDN?

```bash
curl -O https://data.geocode.earth/wof/dist/sqlite/whosonfirst-data-admin-be-latest.db.bz2

lbunzip2 whosonfirst-data-admin-be-latest.db.bz2
```

```
npm install --global @whosonfirst/wof@latest
+ @whosonfirst/wof@0.26.0
```

```
wof sqlite fix whosonfirst-data-admin-be-latest.db
```

**Comment by bboure** [comment]
Thank you @missinglink  I will have a look at this

**Comment by bboure** [comment]
@orangejulius after executing the script and re-importing OSM records, I can confirm the locality is now showing correctly.

```json
        "country": "Belgium",
        "country_gid": "whosonfirst:country:85632997",
        "country_a": "BEL",
        "region": "Brussels-Capital Region",
        "region_gid": "whosonfirst:region:85681713",
        "region_a": "BU",
        "locality": "Brussel",
        "locality_gid": "whosonfirst:locality:1175610569",
```

On a side note, the `wof-admin-lookup` service is getting lots of duplicates in Brussels.
Not sure if this is a related issue.

Thanks!!
