### ISSUE TITLE
lon-lat here vs lat-lon in interpolation

### ISSUE THREAD

**Issue by jeremy-rutman** [pelias/pip-service#107]
the lon:lat format used here  is opposite of what's being used in interpolation , and 'lat-lon' seems to be the more common order .

**Comment by missinglink** [comment]
The Pelias codebase favours `[lon, lat]` ([x,y]) as per the geojson spec.
There is no industry-accepted coordinate ordering, so it's best not to assume anything, refer to the docs if in doubt.
We try to adopt key->value `(?lat=xxx&lon=xxx)` where possible and I believe all other HTTP endpoints adhere to that convention to avoid ambiguities.
