### ISSUE TITLE
using sqlite bundles but pip service not returning locality information in the the /reverse api

### ISSUE THREAD

**Issue by pravink** [pelias/pip-service#114]
My PIP service took 1347.156 seconds to start.

below are the logs
**
2019-10-25T06:14:11.324Z - ESC[32minfoESC[39m: [wof-pip-service:master] locality worker loaded 174903 features in 1
1347.156 seconds
2019-10-25T06:14:11.641Z - ESC[32minfoESC[39m: [wof-pip-service:master] PIP Service Loading Completed!!!
**

Even after this I am seeing lot of missing locality data like below-
**
wof-pip-service:filterOutCitylessNeighbourhoods] skipping 85796997: neighbourhood without locality or localadmin
**

My main concern is /reverse api doesnt return any locality/localadmin/postalcode details in the response. even though i do have admin,venue,postalcode data for whosonfirst [sqlite bundles]

Could you please let me know is there any reason that /v1/search API return locality/localadmin/postalcodes in the response but /v1/reverese doesnt.?

**Comment by missinglink** [comment]
Hi @pravink can you please provide some more information regarding which countries you are loading.

**Comment by pravink** [comment]
@missinglink Thank you for the response.

1. I have imported full planet data for Whosonfirst, openaddress and openstreetmap.
2. for country Australia - with /v1/reverse API i am getting country, region, county, locality, local admin information. 
3. but for country India - I am not getting  locality and  local admin information. 

Let me know if you need any other specific information.

**Comment by orangejulius** [comment]
This is likely caused by the issues with the files distributed from `dist.whosonfirst.org`, as mentioned in https://github.com/pelias/docker/issues/141.

Geocode Earth is now publishing https://geocode.earth/data/whosonfirst and we may update the whosonfirst importer to prefer those (see https://github.com/pelias/whosonfirst/pull/487).
