### ISSUE TITLE
Return Postalcode

### ISSUE THREAD

**Issue by justinsoong** [pelias/pip-service#72]
Seems like neighbourhood,locality,localadmin,county,region,dependency,country,empire,continent are the only things being returned, would like to be able to return more features like postal code

**Comment by justinsoong** [comment]
Am I right to say that anymore features need to be added here?
https://github.com/pelias/wof-admin-lookup/blob/master/src/pip/index.js

**Comment by orangejulius** [comment]
Hey @justinsoong,

As you realized, it's technically quite easy to add postalcodes to this service. However, in most places, using a postal code geometry to "guess" the postalcode for a given point is not correct. Most postalcodes are used to determine postal routes, so the geometries, which are usually derived from addresses, can overlap.

For that reason we have found that it's not generally that useful to load postalcodes in the PIP service. However, I bet there are parts of the world where postalcodes are based on geometry, and in that case it could be quite useful.

**Comment by justinsoong** [comment]
@orangejulius cool thanks for the info :)
