### ISSUE TITLE
Production branch can't find WOF files

### ISSUE THREAD

**Issue by nilsnolde** [pelias/pip-service#93]
For anyone experiencing a similar issue:
The `production` branch is not entirely up-to-date with `WOF` changes yet, similar to a closed issue at [WOF importer](https://github.com/pelias/whosonfirst/issues/400#issue-361940107).

However, `master` branch works as expected, as @orangejulius suggested.

**Comment by nilsnolde** [comment]
Thanks @orangejulius, 

unfortunately no luck:
```bash
git checkout production
sudo rm -rf node_modules/; npm install
sudo systemctl restart pelias-pip.service
sudo systemctl status pelias-pip.service
``` 
Example log:
> Sep 30 15:55:20 ors-pelias-importer npm[6793]: 2018-09-30T15:55:20.024Z - warn: [wof-pip-service:master] unable to locate /srv/pelias_importer_ext/data/wof/meta/wof-region-latest.csv

Switching back to `master` and repeating the above steps works as expected.

**Comment by orangejulius** [comment]
That's very weird. Are you on the latest production code?

Can you please run `npm ls | grep pelias-` on both the master and production branches after repeating those steps, and share the output here?

**Comment by nilsnolde** [comment]
Jup, right, not the latest wof-admin-lookup version.

```bash
ubuntu@ors-pelias-importer:~/pip-service$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

ubuntu@ors-pelias-importer:~/pip-service$ npm ls | grep pelias-
pelias-pip-service@0.0.0-development /home/ubuntu/pip-service
├─┬ pelias-logger@1.3.0
│ ├─┬ pelias-config@3.5.0
├─┬ pelias-mock-logger@1.4.0
├─┬ pelias-wof-admin-lookup@4.13.1
│ ├── pelias-config@3.5.0 deduped
│ ├── pelias-logger@1.3.0 deduped
│ ├─┬ pelias-microservice-wrapper@1.6.0
│ │ ├── pelias-logger@1.3.0 deduped
│ ├─┬ pelias-whosonfirst@2.25.0
│ │ ├─┬ pelias-blacklist-stream@1.0.1
│ │ │ ├── pelias-config@3.5.0 deduped
│ │ ├── pelias-config@3.5.0 deduped
│ │ ├─┬ pelias-dbclient@2.6.0
│ │ │ ├── pelias-config@3.5.0 deduped
│ │ │ ├── pelias-logger@1.3.0 deduped
│ │ ├── pelias-logger@1.3.0 deduped
│ │ ├─┬ pelias-model@5.7.1
│ │ │ ├── pelias-config@3.5.0 deduped
``` 
```bash
ubuntu@ors-pelias-importer:~/pip-service$ git status
On branch production
Your branch is up-to-date with 'origin/production'.

ubuntu@ors-pelias-importer:~/pip-service$ sudo rm -rf node_modules/; npm install

ubuntu@ors-pelias-importer:~/pip-service$ npm ls | grep pelias-
pelias-pip-service@0.0.0-development /home/ubuntu/pip-service
├─┬ pelias-logger@0.4.2
│ ├─┬ pelias-config@3.0.2
├─┬ pelias-mock-logger@1.3.0
├─┬ pelias-wof-admin-lookup@4.6.5
│ ├── pelias-config@3.0.2 deduped
│ ├── pelias-logger@0.4.2 deduped
│ ├─┬ pelias-microservice-wrapper@1.4.0
│ │ ├── pelias-logger@0.4.2 deduped
│ ├─┬ pelias-parallel-stream@0.1.0
│ ├─┬ pelias-whosonfirst@2.22.4
│ │ ├─┬ pelias-config@2.14.0
│ │ ├─┬ pelias-dbclient@2.4.0
│ │ │ ├─┬ pelias-config@2.14.0
│ │ │ ├─┬ pelias-logger@0.3.0
│ │ │ │ ├─┬ pelias-config@2.13.0
│ │ ├─┬ pelias-logger@0.3.1
│ │ │ ├── pelias-config@2.14.0 deduped
│ │ ├─┬ pelias-model@5.3.2
│ │ │ ├─┬ pelias-config@2.14.0
│ │ ├── pelias-parallel-stream@0.1.0 deduped
```

**Comment by orangejulius** [comment]
Oh I know what it is. Please remove `package-lock.json` and that will upgrade you. We _did_ fix that [recently](https://github.com/pelias/pip-service/commit/e5a4f5dc16be9b835e84856abc2498429922979e), and it's not yet in the production branch.

**Comment by nilsnolde** [comment]
Yes, worked! Thanks @orangejulius!

**Comment by orangejulius** [comment]
Hah, well ask @trescube he about that. He started with zero Node.js experience and wrote most of the good parts of Pelias. He only completely broke critical infrastructure in production once, which is more than the rest of us can say :P
